# Generated by Django 4.2.12 on 2024-05-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('precautions', models.TextField()),
                ('prevention_methods', models.TextField()),
                ('medication', models.TextField()),
            ],
        ),
    ]
