# Generated by Django 4.2.12 on 2024-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
    ]
