# Generated by Django 4.2.12 on 2024-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctors_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
