# Generated by Django 4.2.12 on 2024-05-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_diseases_id_alter_doctors_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_phone', models.CharField(max_length=15)),
                ('doctor_advice', models.TextField()),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.diseases')),
            ],
        ),
    ]
